# Global settings
seed: 42
n_jobs: 4
verbose: true

# Paths
data_root: data/
output_dir: outputs/

# Data configuration
data:
  roots:
    raw: "data/raw"
    interim: "data/interim"
    processed: "data/processed"
    external: "data/external"
  datasets: ["SPARK", "SSC", "ABCD"]
  context_fields:
    - fasting
    - collection_clock_time
    - last_dose_hours
    - storage_days
    - fever_72h
    - menstrual_phase
    - recent_illness
    - antibiotics_30d
  ancestry_cols: ["PC1", "PC2", "PC3", "PC4", "PC5"]
  dua_required: true

# Feature configuration
features:
  genetics:
    neurotransmitter_synthesis:
      - TPH1
      - TPH2
      - TH
      - DDC
      - GAD1
      - GAD2
      - COMT
      - MAOA
      - MAOB
    neurotransmitter_transport:
      - SLC6A4
      - SLC6A3
      - SLC6A1
    receptor_genes:
      - DRD1
      - DRD2
      - DRD3
      - DRD4
      - DRD5
      - HTR1A
      - HTR2A
    prs_sets:
      - PRS_autism
      - PRS_ADHD
      - PRS_depression
      - PRS_CRP
      - PRS_BMI
      - PRS_sleep
    structural_variants:
      - CNV_burden
      - SV_burden
      - repeat_expansions
    rare_variants:
      - LoF_burden
      - missense_burden
      - de_novo_variants
    mitochondrial:
      - mtDNA_CN
      - OXPHOS_gene_sets
    epigenetic:
      - HLA_types
      - imprinted_loci

  metabolomics:
    neurotransmitters:
      - serotonin
      - 5-HIAA
      - dopamine
      - DOPAC
      - HVA
      - GABA
      - glutamate
      - glutamine
    kynurenine_pathway:
      - kynurenine
      - kynurenic_acid
      - quinolinic_acid
      - 3-hydroxykynurenine
    acyl_carnitines:
      - C0
      - C2
      - C3
      - C4
      - C5
      - C8
      - C14
      - C16
      - C18
    bile_acids:
      - CA
      - CDCA
      - DCA
      - LCA
      - UDCA
    gut_metabolites:
      - SCFA_acetate
      - SCFA_butyrate
      - SCFA_propionate
      - indoles
      - p_cresol
    micrometabolites:
      - TMAO
      - indoxyl_sulfate
      - p_cresyl_sulfate
    inflammatory_markers:
      - IL1b
      - IL6
      - IL10
      - TNFalpha
      - CRP
      - neopterin
    steroids:
      - cortisol
      - cortisone
      - DHEA_S

  clinical:
    core_instruments:
      - ADOS_score
      - ADI_R_scores
      - SRS_score
      - ADHD_RS_inattentive
      - ADHD_RS_hyperactive
      - Conners_scores
      - CBCL_scores
      - RBS_R
    cognitive:
      - IQ_full
      - IQ_verbal
      - IQ_nonverbal
    sleep:
      - PSQI
      - actigraphy_TST
      - sleep_variability
    endocrine:
      - TSH
      - FT4
      - ferritin
      - vitD_25OH
      - B12
      - folate
    medications:
      - stimulant_type
      - stimulant_dose_mg
      - last_dose_hours
      - SSRI_use
      - antipsychotic_use
      - antibiotics_30d
    comorbidities:
      - tics
      - OCD
      - anxiety
      - depression
      - POTS
      - MCAS

  microbiome:
    diversity:
      - alpha_diversity
      - beta_diversity
    outputs:
      - SCFA_production
      - p_cresol_production
      - indole_production
      - TMAO_production

  imaging:
    EEG:
      - aperiodic_1f_slope
      - alpha_peak_frequency
    MRI_structural:
      - thalamocortical_connectivity
      - cerebellar_volume

  # Prompt 2.1: Autonomic, Circadian, Salivary features
  autonomic:
    hrv_time_domain:
      - SDNN
      - RMSSD
      - pNN50
      - SDANN
      - SDNN_index
    hrv_frequency_domain:
      - LF_power
      - HF_power
      - LF_HF_ratio
      - VLF_power
      - total_power
    hrv_nonlinear:
      - SD1
      - SD2
      - SD1_SD2_ratio
      - sample_entropy
      - approximate_entropy
      - DFA_alpha1
      - DFA_alpha2
    eda:
      - SCL_mean
      - SCL_slope
      - SCR_frequency
      - SCR_amplitude
      - SCR_recovery_time
    cardiovascular:
      - baroreflex_sensitivity
      - blood_pressure_variability
      - orthostatic_response
      - pulse_transit_time
    respiratory:
      - respiratory_rate
      - respiratory_sinus_arrhythmia
      - breathing_pattern_variability

  circadian:
    cortisol:
      - CAR_AUCg
      - CAR_AUCi
      - cortisol_awakening
      - diurnal_slope
      - evening_cortisol
      - total_daily_output
    melatonin:
      - DLMO
      - melatonin_amplitude
      - melatonin_phase
      - phase_angle_difference
    actigraphy:
      - interdaily_stability
      - intradaily_variability
      - relative_amplitude
      - L5_activity
      - M10_activity
      - sleep_regularity_index
    temperature:
      - core_body_temperature_rhythm
      - acrophase
      - amplitude

  salivary:
    biomarkers:
      - alpha_amylase
      - secretory_IgA
      - cortisol
      - testosterone
      - DHEA
      - progesterone
      - estradiol
    inflammatory:
      - CRP_saliva
      - IL1b_saliva
      - IL6_saliva
      - TNFalpha_saliva
    microbiome:
      - oral_microbiome_diversity
      - Streptococcus_abundance
      - pH

  # Prompt 2.2: Environmental & Toxicant features
  environmental:
    air_quality:
      - PM25_pregnancy
      - PM25_early_life
      - PM25_lifetime
      - PM10_exposure
      - NO2_exposure
      - O3_exposure
      - SO2_exposure
    water_quality:
      - nitrate_exposure
      - arsenic_exposure
      - fluoride_level
    traffic:
      - road_proximity_m
      - traffic_density
      - noise_exposure_dB
    green_space:
      - NDVI_500m
      - park_access
      - tree_canopy_percent
    built_environment:
      - walkability_index
      - food_desert_indicator
      - industrial_proximity
    socioeconomic:
      - area_deprivation_index
      - neighborhood_SES
      - census_poverty_rate

  toxicants:
    heavy_metals_hair:
      - Pb_lead
      - Hg_mercury
      - Cd_cadmium
      - As_arsenic
      - Al_aluminum
    heavy_metals_blood:
      - blood_lead
      - blood_mercury
      - blood_cadmium
    essential_metals:
      - Zn_zinc
      - Cu_copper
      - Se_selenium
      - Fe_iron
      - Mn_manganese
    metal_ratios:
      - Cu_Zn_ratio
      - Ca_Mg_ratio
      - Na_K_ratio
      - Hg_Se_ratio
    organic_pollutants:
      - urinary_BPA
      - urinary_BPS
      - phthalate_DEHP
      - phthalate_DBP
      - phthalate_DEP
    pfas:
      - PFOA
      - PFOS
      - PFHxS
      - PFNA
    pesticides:
      - chlorpyrifos_metabolites
      - organophosphate_metabolites
      - pyrethroid_metabolites
    body_burden:
      - toxic_metal_burden_index
      - pollutant_mixture_index

  # Prompt 2.3: Sensory, Interoception, Voice features
  sensory:
    auditory:
      - PTA_left
      - PTA_right
      - gap_detection_threshold
      - P50_gating_ratio
      - ABR_wave_V_latency
      - OAE_present
    visual:
      - contrast_sensitivity
      - motion_coherence_threshold
      - visual_search_slope
      - visual_working_memory_k
    tactile:
      - two_point_discrimination
      - vibrotactile_threshold
      - proprioception_accuracy
      - texture_discrimination
    multisensory:
      - mcgurk_fusion_rate
      - temporal_binding_window
      - sound_induced_flash_rate

  interoception:
    accuracy:
      - heartbeat_counting_accuracy
      - heartbeat_discrimination_d_prime
    sensibility:
      - MAIA2_noticing
      - MAIA2_attention_regulation
      - MAIA2_emotional_awareness
      - MAIA2_self_regulation
      - MAIA2_body_listening
      - MAIA2_trusting
      - BPQ_total
    awareness:
      - interoceptive_awareness
      - confidence_accuracy_correlation

  voice:
    prosodic:
      - pitch_mean_hz
      - pitch_range_hz
      - pitch_variability
      - intensity_mean_db
      - speech_rate_syll_per_sec
      - articulation_rate
      - pause_frequency
    spectral:
      - F1_mean_hz
      - F2_mean_hz
      - F3_mean_hz
      - formant_dispersion
      - jitter_local
      - shimmer_local
      - HNR_db
      - CPP
    temporal:
      - VOT_ms
      - vowel_duration
      - coarticulation_index
    pragmatic:
      - turn_taking_gap
      - prosodic_synchrony
      - emotional_prosody_recognition

# Preprocessing configuration
preprocess:
  imputation: mice_delta
  batch_method: combat
  scaling:
    genetic: standard
    metabolomic: robust
    clinical: standard
    microbiome: clr
    autonomic: standard
    circadian: standard
    salivary: robust
    environmental: quantile
    toxicants: robust
    sensory: standard
    interoception: standard
    voice: robust
  adjust_covariates:
    - age
    - sex
    - BMI
    - pubertal_stage
    - site
    - PC1
    - PC2
    - PC3
    - fasting
    - collection_clock_time
    - last_dose_hours
    - storage_days
  outlier_method: robust_mahalanobis
  outlier_action: winsorize
  missing_threshold: 0.5

# Integration configuration
integrate:
  method: hierarchical
  weights:
    # Distal factors (genetic predisposition, environmental exposures)
    genetic: 0.15
    environmental: 0.08
    toxicants: 0.07
    # Intermediate factors (biological state, processing)
    microbiome: 0.08
    metabolomic: 0.20
    # Proximal factors (physiological state, regulation)
    autonomic: 0.12
    circadian: 0.10
    salivary: 0.05
    # Phenotypic expression (sensory, cognitive)
    sensory: 0.07
    interoception: 0.06
    voice: 0.05
    # Outcome (direct phenotype)
    clinical: 0.02
  hierarchical_levels:
    level1_biological:
      components: [genetic, metabolomic, microbiome, autonomic, circadian, salivary]
      method: PCA
      n_factors: 30
    level2_environmental:
      components: [environmental, toxicants]
      method: PCA
      n_factors: 15
    level3_cognitive_sensory:
      components: [sensory, interoception, voice]
      method: PCA
      n_factors: 15
    level4_clinical:
      components: [clinical]
      method: None
      n_factors: null
  n_factors: 50
  split_by:
    - family_id
    - site
  test_size: 0.2
  time_adjustment:
    enabled: true
    standard_time: 9.0  # Adjust circadian features to 9 AM
    time_sensitive_features:
      - cortisol
      - melatonin
      - core_body_temperature
      - activity_level

# Clustering configuration
cluster:
  embeddings:
    umap:
      n_neighbors: [15, 30, 50]
      min_dist: [0.1, 0.25, 0.5]
      n_components: 2
    tsne:
      perplexity: [10, 30, 50]
      n_components: 2
      n_iter: 2000
  clusterers:
    hdbscan:
      min_cluster_size: 50
      min_samples: 10
    lca:
      n_components: 10
      weight_concentration_prior_type: dirichlet_process
  consensus:
    n_resamples: 100
    agreement_threshold: 65
  topology_enabled: true
  min_gap_score: 1.5
  min_stability: 0.7
  # Anti-pattern-mining features (enabled by default)
  use_consensus: true  # Consensus across parameter sweeps (prevents selection bias)
  test_null_models: true  # Test against permutation/rotation/SigClust nulls
  evaluate_topology_gates: true  # Hard topology gates before subtype claims
  enable_config_locking: true  # Prevent post-hoc parameter tweaking
  baseline_deviation_enabled: true  # Enable baseline-deviation pipeline

# Baseline-Deviation Pipeline
baseline:
  local_pca_components: 5  # Dimensionality of local tangent spaces
  density_percentile: 75.0  # For unsupervised mode: define high-density ridge

# Topology Analysis
topology:
  neighbors: 15  # k-NN graph neighbors for baseline manifold
  rotation_null:
    n_rotations: 200  # Number of rotation-preserving nulls
    preserve_scale: true  # Preserve variance structure
  separation_gate:
    min_score: 0.6  # Minimum separation score to claim discrete subtypes
    min_confidence: 0.5  # Minimum CI lower bound
    n_bootstrap: 200  # Bootstrap samples for CI estimation

# Deviation Threshold
deviation_threshold:
  method: 'null_quantile'  # 'null_quantile' or 'fdr'
  q: 0.99  # 99th percentile for null_quantile method
  fdr_q: 0.05  # FDR level for FDR method

# Validation configuration
validate:
  stability_bootstrap: 100
  external_cohorts:
    - UKB_subset
    - ABCD_holdout
  sensitivity_scenarios:
    - no_meds
    - fasting_only
    - morning_only
    - leave_site_out
    - mnar_sensitivity
    - within_family
  leave_site_out: true
  cross_ancestry: true
  biological_validation: true

# Causal inference configuration
causal:
  mr_instruments:
    - PRS_CRP
    - PRS_BMI
    - PRS_smoking
    - PRS_sleep
  mediation_triplets:
    - exposure: PRS_ADHD
      mediator: kynurenine
      outcome: ADHD_RS_hyperactive
    - exposure: PRS_autism
      mediator: p_cresyl_sulfate
      outcome: SRS_score
    - exposure: rare_variants
      mediator: serotonin
      outcome: symptom_severity
  gxe_pairs:
    - genetic: TPH2
      environment: maternal_SSRI
    - genetic: PRS_autism
      environment: prenatal_infection
    - genetic: rare_variants
      environment: early_life_stress
  dag_enabled: true
  e_value_enabled: true

# Visualization configuration
viz:
  library: plotly
  overlays:
    - cluster
    - diagnosis
    - serotonin_level
    - dopamine_level
    - genetic_burden
    - GI_issues
    - medication_response
  output_formats:
    - html
    - png
  dpi: 300
  theme: colorblind_safe

# Report configuration
report:
  types:
    - executive_summary
    - technical_report
    - clinician_card
  output_formats:
    - markdown
    - html
  include_code: false
  decision_support_enabled: true