# Minimal configuration example for quick testing

seed: 42
n_jobs: 2
verbose: true

data_root: data/
output_dir: outputs/

data:
  roots:
    raw: "data/raw"
    processed: "data/processed"
  datasets: ["SPARK"]
  context_fields:
    - fasting
    - collection_clock_time
  ancestry_cols: ["PC1", "PC2"]
  dua_required: false

features:
  genetics:
    neurotransmitter_synthesis: ["TPH1", "TPH2", "SLC6A4"]
    prs_sets: ["PRS_autism", "PRS_ADHD"]
  metabolomics:
    neurotransmitters: ["serotonin", "dopamine", "GABA"]
    inflammatory_markers: ["IL6", "CRP"]
  clinical:
    core_instruments: ["ADOS_score", "ADHD_RS_inattentive"]
  microbiome:
    outputs: ["SCFA_acetate", "SCFA_butyrate"]
  imaging:
    EEG: ["aperiodic_1f_slope"]

preprocess:
  imputation: knn
  batch_method: combat
  scaling:
    genetic: standard
    metabolomic: robust
  adjust_covariates:
    - age
    - sex

integrate:
  method: stack
  weights:
    genetic: 0.4
    metabolomic: 0.4
    clinical: 0.2

cluster:
  embeddings:
    umap:
      n_neighbors: [30]
      min_dist: [0.25]
      n_components: 2
  clusterers:
    hdbscan:
      min_cluster_size: 20
      min_samples: 5
  consensus:
    n_resamples: 50
    agreement_threshold: 60
  min_gap_score: 1.0
  min_stability: 0.6

validate:
  stability_bootstrap: 50
  external_cohorts: []
  sensitivity_scenarios:
    - no_meds
  leave_site_out: false

causal:
  mr_instruments: ["PRS_CRP"]
  mediation_triplets:
    - exposure: PRS_ADHD
      mediator: dopamine
      outcome: ADHD_RS_inattentive
  gxe_pairs:
    - genetic: TPH2
      environment: maternal_SSRI

viz:
  library: plotly
  overlays:
    - cluster
    - diagnosis
  output_formats:
    - html

report:
  types:
    - executive_summary
  output_formats:
    - markdown
  decision_support_enabled: true