# SPARK (Simons Foundation Powering Autism Research) Dataset Configuration
# Dataset size: 100,000+ individuals with autism
# Data types: genomic (SNP array, WGS), clinical phenotypes
# Access: Application required via SFARI Base

dataset:
  name: "SPARK"
  version: "v2023"  # Update to latest available version
  description: "Simons Foundation Powering Autism Research cohort"
  access_type: "application"
  dua_required: true

  # Data paths (update after download)
  data_root: "data/raw/spark"

  paths:
    # Genomic data
    vcf: "${data_root}/genomics/spark_variants.vcf.gz"
    bfile_prefix: "${data_root}/genomics/spark_plink"  # PLINK binary format

    # Clinical/phenotype data
    phenotypes: "${data_root}/phenotypes/spark_phenotypes.csv"
    demographics: "${data_root}/phenotypes/spark_demographics.csv"
    assessments: "${data_root}/phenotypes/spark_assessments.csv"

    # Family structure
    pedigree: "${data_root}/family/spark_pedigree.fam"

    # QC reports (if provided)
    qc_reports: "${data_root}/qc/"

# Phenotype variable mappings (harmonize to standard names)
phenotype_mapping:
  sample_id: "spid"
  family_id: "family_id"
  individual_id: "individual_id"

  # Demographics
  age: "age_at_assessment"
  sex: "sex"  # 1=male, 2=female
  race: "race"
  ethnicity: "ethnicity"

  # Diagnosis
  autism_diagnosis: "asd_diagnosis"  # 1=yes, 0=no
  diagnosis_confidence: "diagnosis_confidence"

  # Assessments
  scq_total: "scq_total_score"
  srs_total: "srs_total_t_score"
  ados_module: "ados_module"
  ados_css: "ados_calibrated_severity_score"
  adi_r_total: "adi_r_total"

  # Comorbidities
  adhd: "adhd_diagnosis"
  intellectual_disability: "id_diagnosis"
  anxiety: "anxiety_diagnosis"
  epilepsy: "epilepsy_diagnosis"

  # Developmental history
  age_first_words: "age_first_words_months"
  age_first_phrases: "age_first_phrases_months"
  developmental_regression: "regression_flag"

# Genomic data configuration
genomics:
  reference_build: "GRCh38"  # or GRCh37, check with data provider

  # QC parameters
  qc:
    sample_call_rate: 0.95
    snp_call_rate: 0.95
    maf_threshold: 0.01
    hwe_pvalue: 1e-6

  # Variant filtering
  filtering:
    remove_indels: false
    remove_multiallelic: false
    min_qual: 30
    min_depth: 10

  # Imputation (if needed)
  imputation:
    enabled: true
    reference_panel: "TOPMed"  # or 1000G Phase 3
    method: "minimac4"

# Clinical data configuration
clinical:
  # Missing value codes
  missing_codes: [-9, -99, "NA", ""]

  # Inclusion criteria
  inclusion:
    autism_diagnosis: true
    age_range: [2, 100]  # Age in years
    has_genomic_data: true

  # Exclusion criteria
  exclusion:
    syndromic_autism: false  # Set to true to exclude syndromic cases

# Preprocessing configuration
preprocessing:
  # Imputation strategy for missing clinical data
  imputation_strategy: "knn"  # knn, mean, median, mice

  # Scaling
  scaling_method: "standard"  # standard, robust, minmax

  # Outlier detection
  outlier_detection:
    enabled: true
    method: "isolation_forest"
    contamination: 0.05

# Integration configuration
integration:
  # Modalities to include
  modalities:
    - genomic
    - clinical

  # Integration method
  method: "mofa"
  n_factors: 15

  # Batch correction
  batch_correction:
    enabled: true
    batch_variable: "sequencing_center"
    method: "combat"

# Clustering configuration
clustering:
  method: "hdbscan"
  min_cluster_size: 50  # Larger for big cohort
  min_samples: 10
  metric: "euclidean"

  # UMAP embedding
  embedding:
    n_neighbors: 30
    min_dist: 0.1
    n_components: 2

# Validation configuration
validation:
  n_bootstrap: 100
  n_permutations: 1000
  compute_stability: true

  # Cross-validation
  cv_folds: 5
  cv_repeats: 10

# Output configuration
output:
  base_dir: "outputs/spark"

  directories:
    preprocessed: "${base_dir}/preprocessed"
    integrated: "${base_dir}/integrated"
    clusters: "${base_dir}/clusters"
    validation: "${base_dir}/validation"
    figures: "${base_dir}/figures"
    reports: "${base_dir}/reports"

# Reporting configuration
report:
  title: "SPARK Dataset Analysis"
  author: "AuDHD Correlation Study"
  include_metadata: true
  include_pdf: false

  # Figures to include
  figures:
    - cluster_umap
    - cluster_heatmap
    - stability_metrics
    - pathway_enrichment
    - cluster_characteristics

# Reproducibility
reproducibility:
  seed: 42
  save_checkpoints: true
  checkpoint_dir: "${output.base_dir}/checkpoints"
  log_file: "${output.base_dir}/analysis.log"

# Computational resources
compute:
  n_cores: 8  # Adjust based on available resources
  memory_gb: 32
  use_gpu: false

# Notes and caveats
notes: |
  SPARK is the largest autism genetic cohort.

  Important considerations:
  - Family structure: Many probands with unaffected siblings
  - Recruitment bias: Online recruitment may affect generalizability
  - Phenotype depth varies: Not all participants have all assessments
  - Genomic data types: Mix of SNP array and WGS
  - Ongoing recruitment: Check for updated data releases

  Access:
  1. Apply via sparkforautism.org
  2. Execute DUA
  3. Download from SFARI Base portal

  Citation:
  SPARK Consortium (2018). SPARK: A US Cohort of 50,000 Families to
  Accelerate Autism Research. Neuron, 97(3), 488-493.